name: musicplayer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0-262.0.dev <4.0.0'


dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.4
  get: 
  flutter: 
    sdk: flutter
  just_audio: ^0.9.36
  rxdart: ^0.27.7
  on_audio_query: ^2.9.0
  permission_handler: ^11.0.1

  #hive 
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  path_provider_android: ^2.2.1
  path_provider: ^2.1.1
  
  file_picker: ^5.3.1
  marquee: ^2.2.3
  just_audio_background: ^0.0.1-beta.11
  sleek_circular_slider: ^2.0.1
  shared_preferences: ^2.2.2
  audio_video_progress_bar: ^2.0.1
  audio_service: ^0.18.12
  
  
  
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/music icon.png"
  
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter: 
  uses-material-design: true
  
  assets:
   - assets/


